name: BuildHID
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Publish
        run: dotnet publish -c Release --self-contained true -p:PublishSingleFile=true
      - name: ExportEXE
        uses: actions/upload-artifact@v4
        with:
          path: bin/Release/net48/publish/SimplerHidWrite.exe
