name: BuildHID
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: VSBuild
        uses: microsoft/vs-build@v1
        with:
          solution: SimplerHidWrite.sln
          configuration: Release
      - name: 导出EXE
        uses: actions/upload-artifact@v4
        with:
          path: '**/Release/SimplerHidWrite.exe'
